source 'https://rubygems.org'

gem 'rails', '4.1.16'
gem 'pg'
gem 'devise'
gem 'simple_token_authentication', '~> 1.0'
gem 'fb_graph2'
gem 'unicode_utils'
gem 'acts_as_api'
gem 'rack-cors', :require => 'rack/cors'

# Use Capistrano for deployment
gem 'capistrano', require: false
gem 'capistrano-rbenv', require: false
gem 'capistrano_colors', require: false

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'better_errors'
  gem 'thin'
end

group :production do
  gem 'exception_notification'
end

